### ISSUE TITLE
Java version changes

### ISSUE THREAD

**Issue by Mirka-exe** [SQA-Tetris/Tetris#10]
Java version seems to change every time I pull code. All of the development team have been programming in Java 11 up until now. However the version sometimes changes to java 10.

Can this be looked into by the Git master and QA manager?

**Comment by JamesArmer** [comment]
It could be to do with the version of Java being used at runtime. I would check the version of your IntelliJ under the help tab as well as checking for any updates. I have also found a help page where you can install a plugin to change the version of Java at runtime : https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under
