### ISSUE TITLE
Package management and imports not functioning correctly.

### ISSUE THREAD

**Issue by Sneakercopter** [SQA-Tetris/Tetris#2]
- Cannot import Swing libraries correctly into IntelliJ
- Code is not compiling as a result
- Swing libraries cannot be resolved despite the jar files being present

**Comment by JamesArmer** [comment]
Incorrectly assigned to me (QA Manager), reassigning to the developer @Mirka-S

**Comment by Mirka-exe** [comment]
Error occured in commit: [a6c7a420ef](https://github.com/SQA-Tetris/Tetris/tree/a6c7a420ef9f9e290e9c5eca864fda1641371d7b)
Has been resolved in: [d251f5a8ea](https://github.com/SQA-Tetris/Tetris/tree/d251f5a8ea1b2707fb49758777a393cd288497ab)
