### ISSUE TITLE
Null pointer when running Board.java

### ISSUE THREAD

**Issue by Sneakercopter** [SQA-Tetris/Tetris#3]
- Null pointer during piece drop simulation in commit [a07757adfeae3a04eff8a5e143794f2f555d7c60](https://github.com/SQA-Tetris/Tetris/commit/a07757adfeae3a04eff8a5e143794f2f555d7c60)

**Comment by Mirka-exe** [comment]
Error occured in: [0fbb3fea8d](https://github.com/SQA-Tetris/Tetris/tree/0fbb3fea8d7044a45277f7b20e584272e19f14d4)
Error supposedly fixed in: [905f42e3a1](https://github.com/SQA-Tetris/Tetris/tree/905f42e3a1bff6c33e4519d225f4781b498861d2)

@mikeynic Please test if the problem has been resolved
