### ISSUE TITLE
Keyboard inputs not working

### ISSUE THREAD

**Issue by Sneakercopter** [SQA-Tetris/Tetris#6]
After reviewing against customer requirements it has come to my attention that the keyboard inputs do not work for moving the shapes. Is this intentional behavior? 

The specific requirement in question is:

-I want to be able to rotate shapes clockwise

**Comment by Mirka-exe** [comment]
This implementation is the next goal on the development team, it will be delivered as soon as possible.

**Comment by Mirka-exe** [comment]
As of commit [82633a6b80](https://github.com/SQA-Tetris/Tetris/tree/82633a6b80f51db65bf6a66034be1e59c5c53efb) all keyboard controls including movement have been added to the game
